name: Update Apple Music Playlist

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Puppeteer dependencies
        uses: browser-actions/setup-chrome@v2

      - name: Check Chrome version
        run: chrome --version
    
      - name: Clone Apple Music Scraper repository
        run: |
          git clone https://github.com/Tritounet1/apple-music-playlist-scraper.git scraper
          cd scraper

      - name: Install dependencies
        run: |
          cd scraper
          npm install

      - name: Create .env file
        run: |
          cd scraper
          cat > .env << EOF
          PLAYLIST_URL=https://music.apple.com/fr/playlist/playlist-general/pl.u-vxy6kvMt82a24y0
          NUMBER_OF_TRACKS=5
          EOF

      - name: Build TypeScript
        run: |
          cd scraper
          npm run build

      - name: Run Apple Music scraping
        run: |
          cd scraper
          # Configure Puppeteer to use the installed Chrome and disable sandbox
          export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
          export PUPPETEER_EXECUTABLE_PATH=/opt/hostedtoolcache/setup-chrome/chrome/stable/x64/chrome
          node dist/index.js

      - name: Create svg image
        run: |
          cd scraper
          node dist/test.js

      - name: Copy updated files to current repository
        run: |
          cp -r scraper/playlist-top5.svg ./assets/
          cp scraper/playlist_tracks.json ./datas/

      - name: Clean up scraper folder
        run: rm -rf scraper
        
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "feat: 🎵 Update Currently Listening section"
          git push 